= Writers Write: The Documentation BOF

[abstract]
--
// tag:abstract[]
People often say that documentation is boring.
Not us!
Let's talk about documentation.
How do you write it?
How do you publish it?
What tools do you use?
How do you encourage other people to write?
Let's share ways to get other people to love and appreciate documentation just as we do.
// end:abstract[]
--

== Resources

* https://gist.github.com/mojavelinux/f66397404a80507ce5d25c3b7add3a26[Topic ideas]
* https://gist.github.com/mojavelinux/386cccaa38915a58f2fc3943276ddb8a[Notes from Devoxx Belgium, 2016]
* http://docslikecode.com/[Docs Like Code] -- A book about best practices for writing docs using development tools and techniques.

== View slides locally

First, ensure you have the following installed:

. http://nodejs.org[Node.js]
. http://gulpjs.com[Gulp CLI]

 $ npm install -g gulp-cli

. https://www.ruby-lang.org/[Ruby >= 2]

 $ rvm use 2.4.1 --install

. http://bundler.io/[Bundler]

 $ gem install bundler

Next, install dependencies (if not already installed by the generator):

 $ npm install
   bundle install --path=.bundle/gems

Finally, build and serve the presentation!

 $ gulp serve
